services:

  api:
    container_name: nomad-api
    image: node:22-alpine3.18
    command: npm run start
    working_dir: /src
    volumes:
      - ./:/src
      - ./node_modules:/src/node_modules
    env_file: .env
    ports:
      - 3000:3000
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_SERVICE_NAME=nomad-api
      - OTEL_RESOURCE_ATTRIBUTES=service.name=nomad-api
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/jaeger:2.3.0
    ports:
      - "16686:16686"
      - "4318:4318"
      - "4317:4317"
      - "5778:5778"
      - "9411:9411"
    environment:
      - LOG_LEVEL=debug
    