services:

  api:
    container_name: nomad-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    env_file: .env.example
    ports:
      - 3000:3000
