name: CI
on: push
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm ci

    - name: Run linter
      run: npm run lint

  tests:
    needs: linter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-type: [unit, e2e]
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm ci

    - name: Run tests
      run: npm run test:${{ matrix.test-type }}